# Generated by Django 5.0.7 on 2024-07-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_The_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descriptions', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CatagoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mane_Cat_Image', models.ImageField(upload_to='cat_image')),
                ('Womane_Cat_Image', models.ImageField(upload_to='cat_image')),
                ('Kids_Cat_Image', models.ImageField(upload_to='cat_image')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Address', models.CharField(max_length=256)),
                ('Telegram', models.CharField(max_length=50)),
                ('Descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Linkdin', models.TextField()),
                ('Telegram', models.TextField()),
                ('Github', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone1', models.TextField()),
                ('Phone2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title1', models.CharField(max_length=100)),
                ('Title2', models.CharField(max_length=100)),
                ('Title3', models.CharField(max_length=100)),
                ('Title4', models.CharField(max_length=100)),
                ('Large_Logo', models.ImageField(upload_to='hero')),
                ('Small_Logo', models.ImageField(upload_to='hero')),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Profile_Picture', models.ImageField(upload_to='navbar')),
                ('Image', models.ImageField(upload_to='navbar')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_Name', models.CharField(max_length=100)),
                ('Account_Number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_New', models.BooleanField(default=False)),
                ('is_Popular', models.BooleanField(default=False)),
                ('Stoke_Quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Image', models.ImageField(upload_to='product')),
                ('Rate', models.FloatField()),
                ('category', models.CharField(choices=[('Womens', 'Womens'), ('Mens', 'Mens'), ('Kids', 'Kids')], max_length=10)),
            ],
        ),
    ]
