# Generated by Django 5.0.7 on 2024-07-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='Title',
        ),
    ]
